name: yamel
on:
    push:
        branches: [ master ]

    workflow_dispatch:
   
env:
    maven_packages_cache: ".m2/repository"
    MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"
   
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Cache Maven Packages
              uses: actions/cache@v2
              with:
                path: $maven_packages_cache
                key: ${{runner.os}}-build
                
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Build Servlet
              run: mvn compile
              
            - name: Upload Artifact for next Jobs 
              uses: actions/upload-artifact@master
              with:
                name: target-$CI_COMMIT_SHA # target-69420d.zip
                path: target/*
    
    
    test:
        needs:
            - build
        runs-on: self-hosted
        steps:                    
            - name: Run Unit-Tests
              run: mvn test
        
    package:
        needs:
            - build
        runs-on: self-hosted
        steps:
            - name: Cache Maven Packages
              uses: actions/cache@v2
              with:
                path: $maven_packages_cache
                key: ${{runner.os}}-build
                
            - uses: actions/download-artifact@master
              with:
                name: target-$CI_COMMIT_SHA # target-69420d.zip
                path: target/*
                
            - name: Create Package
              run: mvn package
            - uses: actions/upload-artifact@master
              with:
                name: war-$CI_COMMIT_SHA # war-69420d.zip
                path: target/*.war
    
    
    deploy:
        needs:
            - package
        runs-on: self-hosted
        environment:
            name: test
            url: http://localhost:8081/game2048
        steps:
            - name: Start Servlet
              run: echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps'
    
            
        
