name: yamel
on:
    push:
        branches: [ master ]

    workflow_dispatch:
   
env:
    maven_packages_cache: ".m2/repository"
   
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Cache Maven Packages
              uses: actions/cache@v2
              with:
                path: $maven_packages_cache
                key: ${{runner.os}}-build
                
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Build Servlet
              run: mvn compile
              
            - name: Upload Artifact for [test, package] 
              uses: actions/upload-artifact@v2
              with:
                name: target
                path: "target/*"
    
    
    test:
        needs:
            - build
        runs-on: self-hosted
        steps:
            - name: Cache Maven Packages
              uses: actions/cache@v2
              with:
                path: $maven_packages_cache
                key: ${{runner.os}}-build
                
            - name: Run Unit-Tests
              run: mvn test
        
    package:
        needs:
            - build
        runs-on: self-hosted
        steps:
            - name: Cache Maven Packages
              uses: actions/cache@v2
              with:
                path: $maven_packages_cache
                key: ${{runner.os}}-build
                
            - name: Create Package
              run: mvn package -Dmaven.test.skip=true
              
            - name: Upload Artifact for deploy_test
              uses: actions/upload-artifact@v2
              with:
                name: war
                path: "target/*.war"
    
    deploy_test:
        needs:
            - package
        runs-on: self-hosted
        environment:
            name: Super Cool Testing Environment
            url: http://localhost:8081/game2048
        steps:
                
            - name: Start Servlet
              run: cp -f ./target/game2048.war /usr/local/tomcat/webapps
