name: yamel
on:
    push:
        branches: [ master ]

    workflow_dispatch:
   
env:
    maven_packages_cache: ".m2/repository"
    # MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"
   
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Cache Maven Packages
              uses: actions/cache@v2
              with:
                path: $maven_packages_cache
                key: ${{runner.os}}-build
                
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Build Servlet
              run: mvn compile
              
            - name: Upload Artifact for [test, package] 
              uses: actions/upload-artifact@v2
              with:
                name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
                path: target/*
    
    
    test:
        needs:
            - build
        runs-on: self-hosted
        steps:                    
            - name: Run Unit-Tests
              run: mvn test
        
    package:
        needs:
            - build
        runs-on: self-hosted
        steps:
            - name: Cache Maven Packages
              uses: actions/cache@v2
              with:
                path: $maven_packages_cache
                key: ${{runner.os}}-build
                
            - name: Create Package
              run: mvn package
              
            - name: Upload Artifact for Deploy
              uses: actions/upload-artifact@v2
              with:
                name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
                path: target/*.war
    
    
    deploy_test:
        needs:
            - package
        runs-on: self-hosted
        environment:
            name: Super Cool Testing Environment
            url: http://localhost:8080/game2048
        steps:
            - name: Start Servlet
              run: echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps'
    
            
        
