name: deployment-workflow
on: push

jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
      - name: Cache Build Stuff
        uses: actions/cache@v2
        with:
          path: ".m2/repository"
          key: ${{runner.os}}-build
      - uses: actions/checkout@v2
      - run: mvn compile
      - name: Upload build stuff for job 1
        uses: actions/upload-artifact@v2
        with:
          name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA # build-main-12534f4.zip
          path: "target/*"

  test:
    name: test
    runs-on: self-hosted
    needs: build
    steps:
      - run: mvn test

  package:
    name: package
    runs-on: self-hosted
    needs: test
    steps:
      - name: Cache Package Stuff
        uses: actions/cache@v2
        with:
          path: ".m2/repository"
          key: ${{runner.os}}-package
      - run: mvn package
      - name: Package Artifact from maven
        uses: actions/upload-artifact@v2
        with:
         name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA # build-main-12534f4.zip
         path: "target/*.war"

  deploy_test:
    name: deploy_test
    runs-on: self-hosted
    needs: package
    environment:
      name: test
      url: http://localhost:8081/game2048
    steps:
      - run: echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps'
